[build]
  command = "cd frontend && npm install && CI=false npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_juacode-nextjs-app/:splat"
  status = 200
  force = true